spring.application.name=backend
# ==============================================================
# 1. DATASOURCE CONFIG (SUPABASE)
# ==============================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bicupmuqmzeexpelknjq
spring.datasource.password=DoAnTotNghiep
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# 2. JPA / HIBERNATE CONFIG
# ==============================================================
# 'update': T? ??ng s?a b?ng n?u code thay ??i (Ch? d?ng l?c Dev)
# 'validate': Ch? ki?m tra xem code c? kh?p DB kh?ng (Khuy?n d?ng v? b?n ?? t?o DB r?i)
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? c?u l?nh SQL trong Console ?? d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect chu?n cho Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gi?i h?n s? l??ng k?t n?i t?i ?a xu?ng 5 (M?c ??nh là 10, r?t d? gây ??y DB Cloud)
spring.datasource.hikari.maximum-pool-size=5

# Th?i gian s?ng t?i ?a c?a 1 k?t n?i (gi?m xu?ng ?? nó nhanh d?n d?p)
spring.datasource.hikari.max-lifetime=600000

# ==============================================================
# 3. SERVER CONFIG
# ==============================================================
server.port=8080
# Cho ph?p hi?n th? message l?i chi ti?t (d? debug)
spring.web.error.include-message=always
# ==============================================================
# 4. JWT CONFIGURATION
# ==============================================================
# ??y l? chu?i b? m?t ?? k? Token (Ph?i ?? d?i v? ng?u nhi?n)
app.jwtSecret=SuperSecretKeyForThesisProject2026MustBeVeryLongAndSecureToAvoidErrors
# Th?i gian h?t h?n Token (ms) - V? d?: 86400000 = 1 ng?y
app.jwtExpirationMs=3600000
# ===============================
# C?U H?NH G?I EMAIL (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hanzoalizer@gmail.com
spring.mail.password=aqjd iqnl tzzl rktv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Cho phép upload ?nh t?i ?a 5MB
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB